### ISSUE TITLE
--keep-container option

### ISSUE THREAD

**Issue by viktomas** [realestate-com-au/harpoon#14]
It would be great if there was some way how to tell harpoon not to delete containers when it's finished.

One possible scenario is:
Tests running in docker container are passing even though they shouldn't and I want to quickly check test database after mentioned test run is finished. I would run docker with --keep-container option and would be able commit db container afterwards.

**Comment by delfick** [comment]
if you upgrade to 0.5.3.6 then you'll get `--no-cleanup` and `--intervene-afterwards`

`--no-cleanup` will mean that no images are removed at the end of the run.

`--intervene-afterwards` will mean that the main container will be "intervened" after it's run along with all links and shared volumes that it was initially run with.

:)
