### ISSUE TITLE
harpoon won't start

### ISSUE THREAD

**Issue by cplim** [realestate-com-au/harpoon#15]
I keep getting the following error running harpoon

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Something went wrong! -- BadDockerConnection
	"Failed to connect to docker"	base_url=https://192.168.59.105:2376	error=[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

OS: Mac OSX Yosemite
Python: 2.7.9
Openssl: 1.0.2a-1
Boot2docker: 1.6.0
docker: 1.6.0

**Comment by delfick** [comment]
Interesting.

That's not the only error you'll get with 1.6 btw, I need to do a release to fix a problem with interactive prompts.

The certificate verify failing I haven't seen before though, that's interesting.

Try removing ~/.boot2docker and doing a boot2docker init again and see if it regenerates the certificate.

**Comment by delfick** [comment]
@cplim harpoon 0.5.5.4 contains the fix for it to work with docker 1.6 :)

**Comment by cplim** [comment]
Unfortunately the error is still there. I even upgraded *virtualenv* to the latest (12.1.1) just in case. Is there a verbose mode that I can set as options/cmd line?

**Comment by braidenjudd** [comment]
I'm getting below with python 2.7.6. It is just a warning it works.

/Users/braiden.judd/dev/building-profile-ui/docker/.harpoon/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

**Comment by cplim** [comment]
I was getting the same message with python 2.7.8, but it was still coming up as an error. As a consequence of that I upgraded to python 2.7.9 as recommended by urllib3 (https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning) and I am now getting the CERTIFICATE_VERIFY_FAILED error.

**Comment by delfick** [comment]
Perhaps https://github.com/docker/docker-py/issues/465 is related.

Try ``brew switch openssl 1.0.1j``

**Comment by cplim** [comment]
Managed to install openssl-1.0.1m, however I had to use the following command:

```
brew install openssl101
brew link --force openssl101
```

harpoon now works. However I am still getting an error on harpoon:ship:context.py line 100. Error was:

UnicodeEncodeError: 'ascii' codec can't encode characters in position 147-157: ordinal not in range(128)

I think I'll raise another issue for this. Thanks.

**Comment by delfick** [comment]
Cool, no probs
